-   id: checkmake
    name: Makefile linter/analyzer
    entry: checkmate
    language: golang
    additional_dependencies:
    -   github.com/mrtazz/checkmake
    -   github.com/docopt/docopt-go
    -   github.com/olekukonko/tablewriter
    files: Makefile
